### ISSUE TITLE
s3 endpoint can't connect 

### ISSUE THREAD

**Issue by hale177** [UmfintechWtc/ansible-s3_file_transfer#1]
**run output** 

```
TASK [ci : save artifact] ******************************************************
fatal: [node-1]: FAILED! => {"changed": false, "msg": "Unknown error occurred: Could not connect to the endpoint URL: \"[http://http://192.168.0.151:31900\](http://http//192.168.0.151:31900/)""}
```

**my playbook task** 
```
- name: upload files 
  s3_file_transfer:
    ak: *******
    sk: **********
    dest: "artifact/deploy-{{ p_tag }}-{{ p_num }}.tgz"
    src: "/data/ci/build/deploy-{{ p_tag }}-{{ p_num }}.tgz"
    state: "upload"
    endpoint_url: "http://192.168.0.151:31900"
  when: 'build_node in inventory_hostname'
  
```

but endpoint is  always ok  
![image](https://github.com/user-attachments/assets/b2e226a9-8904-42bc-bfa5-f92ee29b0537)

need your help ，thks
